# Generated by Django 3.2.9 on 2021-12-20 13:14

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pflops', '0022_auto_20211211_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(db_index=True, default=None, null=True)),
                ('name', models.TextField(db_index=True)),
                ('level', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('key_digit', models.CharField(default=None, max_length=32, null=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('full_name', models.TextField(db_index=True, default=None, null=True)),
                ('quantity', models.FloatField(default=1.0)),
                ('rate', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
                ('to_pflops', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.parameter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('print_name', models.TextField(db_index=True, default=None, null=True)),
                ('to_pflops', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.unit')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_key', models.TextField(db_index=True, default=None, null=True)),
                ('party_key', models.TextField(db_index=True, default=None, null=True)),
                ('part_number', models.TextField(db_index=True, default=None, null=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('short_name', models.TextField(db_index=True, default=None, null=True)),
                ('name_rus', models.TextField(db_index=True, default=None, null=True)),
                ('name_other', models.TextField(db_index=True, default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('warranty', models.TextField(default=None, null=True)),
                ('url', models.TextField(db_index=True, default=None, null=True)),
                ('ean_128', models.TextField(db_index=True, default=None, null=True)),
                ('upc', models.TextField(db_index=True, default=None, null=True)),
                ('pnc', models.TextField(db_index=True, default=None, null=True)),
                ('hs_code', models.TextField(db_index=True, default=None, null=True)),
                ('gtin', models.TextField(db_index=True, default=None, null=True)),
                ('tnved', models.TextField(db_index=True, default=None, null=True)),
                ('traceable', models.BooleanField(db_index=True, default=None, null=True)),
                ('weight', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('width', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('height', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('depth', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('volume', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('multiplicity', models.IntegerField(default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('content_loaded', models.DateTimeField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.category')),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
                ('to_pflops', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.product')),
            ],
            options={
                'ordering': ['vendor__name', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
                ('to_pflops', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('to_pflops', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.unit')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.TextField(db_index=True, default=None, null=True)),
                ('file_name', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.product')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.vendor'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.currency')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search', models.TextField(db_index=True, default=None, null=True)),
                ('must_keep_end_user_price', models.BooleanField(db_index=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('quantity_great_than', models.BooleanField(db_index=True, default=None, null=True)),
                ('can_reserve', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_available_for_order', models.BooleanField(db_index=True, default=None, null=True)),
                ('unconditional', models.BooleanField(db_index=True, default=False)),
                ('sale', models.BooleanField(db_index=True, default=False)),
                ('promo', models.BooleanField(db_index=True, default=False)),
                ('outoftrade', models.BooleanField(db_index=True, default=False)),
                ('condition_description', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.location')),
                ('price', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price', to='distributors.price')),
                ('price_in', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price_in', to='distributors.price')),
                ('price_out', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price_out', to='distributors.price')),
                ('price_out_open', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price_out_open', to='distributors.price')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.product')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.unit')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
                ('parameter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.parameter')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.product')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.parameterunit')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='distributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='to_pflops',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.category'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='party_search_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('distributor', 'name')},
        ),
    ]
