# Generated by Django 3.2.5 on 2021-08-25 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_remove_category_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
