# Generated by Django 3.2.5 on 2021-08-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='distributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor'),
        ),
    ]
