# Generated by Django 3.2.5 on 2021-08-26 04:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0005_vendor_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_key', models.TextField(db_index=True, default=None, null=True)),
                ('party_key', models.TextField(db_index=True, default=None, null=True)),
                ('article', models.TextField(db_index=True, default=None, null=True)),
                ('name', models.TextField(db_index=True)),
                ('name_rus', models.TextField(db_index=True, default=None, null=True)),
                ('name_other', models.TextField(db_index=True, default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('eaN128', models.TextField(db_index=True, default=None, null=True)),
                ('upc', models.TextField(db_index=True, default=None, null=True)),
                ('pnc', models.TextField(db_index=True, default=None, null=True)),
                ('hsCode', models.TextField(db_index=True, default=None, null=True)),
                ('traceable', models.BooleanField(db_index=True, default=None, null=True)),
                ('condition_description', models.TextField(default=None, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.category')),
                ('condition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.condition')),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
                ('vendor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
