# Generated by Django 3.2.5 on 2021-08-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0006_condition_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='eaN128',
            new_name='ean_128',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hsCode',
            new_name='hs_code',
        ),
    ]
