# Generated by Django 3.2.5 on 2021-08-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0007_auto_20210826_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['vendor__name', 'article']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='multiplicity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True),
        ),
    ]
