# Generated by Django 3.2.5 on 2021-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0008_auto_20210826_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
