# Generated by Django 3.2.5 on 2021-08-26 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0009_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('print_name', models.TextField(db_index=True, default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
