# Generated by Django 3.2.5 on 2021-08-28 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0010_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
