# Generated by Django 3.2.5 on 2021-08-28 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0011_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('print_name', models.TextField(db_index=True, default=None, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['key']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_in', models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True)),
                ('price_out', models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True)),
                ('price_out_open', models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True)),
                ('must_keep_end_user_price', models.BooleanField(db_index=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('quantity_great_than', models.BooleanField(db_index=True, default=None, null=True)),
                ('can_reserve', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_available_for_order', models.BooleanField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency_in', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.currency')),
                ('currency_out', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.currency')),
                ('currency_out_open', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.currency')),
                ('distributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.location')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.product')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.unit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.unit'),
        ),
    ]
