# Generated by Django 3.2.6 on 2021-08-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0012_auto_20210828_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['created']},
        ),
    ]
