# Generated by Django 3.2.5 on 2021-08-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0013_alter_party_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
    ]
