# Generated by Django 3.2.5 on 2021-08-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0014_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_loaded',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
