# Generated by Django 3.2.5 on 2021-09-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0016_auto_20210831_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='article',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
