# Generated by Django 3.2.7 on 2021-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0017_category_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='slug',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
