# Generated by Django 3.2.7 on 2021-09-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0018_auto_20210911_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='slug',
        ),
    ]
