# Generated by Django 3.2.7 on 2021-09-12 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0019_auto_20210912_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
