# Generated by Django 3.2.7 on 2021-09-19 19:41

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0022_auto_20210914_1558'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddField(
            model_name='party',
            name='search',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='party',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='party_search_idx'),
        ),
    ]
