# Generated by Django 3.2.7 on 2021-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0023_auto_20210919_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='search',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
