# Generated by Django 3.2.7 on 2021-09-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0024_alter_party_search'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='party',
            name='party_search_idx',
        ),
    ]
