# Generated by Django 3.2.7 on 2021-09-20 16:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0025_remove_party_party_search_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='party',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='party_search_idx'),
        ),
    ]
