# Generated by Django 3.2.7 on 2021-09-23 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0027_remove_vendor_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='currency_in',
        ),
        migrations.RemoveField(
            model_name='party',
            name='currency_out',
        ),
        migrations.RemoveField(
            model_name='party',
            name='currency_out_open',
        ),
        migrations.RemoveField(
            model_name='party',
            name='must_keep_end_user_price',
        ),
        migrations.RemoveField(
            model_name='party',
            name='price_in',
        ),
        migrations.RemoveField(
            model_name='party',
            name='price_out',
        ),
        migrations.RemoveField(
            model_name='party',
            name='price_out_open',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.currency')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
