# Generated by Django 3.2.7 on 2021-09-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0028_auto_20210923_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='must_keep_end_user_price',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='price',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.price'),
        ),
        migrations.AddField(
            model_name='party',
            name='price_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.price'),
        ),
        migrations.AddField(
            model_name='party',
            name='price_out',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.price'),
        ),
        migrations.AddField(
            model_name='party',
            name='price_out_open',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.price'),
        ),
    ]
