# Generated by Django 3.2.7 on 2021-09-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0029_auto_20210923_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='price',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price', to='distributors.price'),
        ),
        migrations.AlterField(
            model_name='party',
            name='price_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price_in', to='distributors.price'),
        ),
        migrations.AlterField(
            model_name='party',
            name='price_out',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price_out', to='distributors.price'),
        ),
        migrations.AlterField(
            model_name='party',
            name='price_out_open',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_price_out_open', to='distributors.price'),
        ),
    ]
