# Generated by Django 3.2.7 on 2021-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0030_auto_20210923_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unconditional',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
