# Generated by Django 3.2.7 on 2021-09-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0031_auto_20210926_0735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
