# Generated by Django 3.2.7 on 2021-09-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0032_delete_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.TextField(default=None, null=True),
        ),
    ]
