# Generated by Django 3.2.7 on 2021-09-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0033_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='distributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor'),
        ),
    ]
