# Generated by Django 3.2.7 on 2021-09-26 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0035_auto_20210926_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='tnved',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
