# Generated by Django 3.2.7 on 2021-09-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0036_auto_20210926_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.distributor'),
        ),
    ]
