# Generated by Django 3.2.7 on 2021-10-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0037_location_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='ext',
            field=models.TextField(default=None, null=True),
        ),
    ]
