# Generated by Django 3.2.7 on 2021-10-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0038_productimage_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='print_name',
        ),
    ]
