# Generated by Django 3.2.7 on 2021-10-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0004_auto_20211003_0925'),
        ('distributors', '0039_remove_unit_print_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='pflops_vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.vendor'),
        ),
    ]
