# Generated by Django 3.2.7 on 2021-10-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0005_vendor_slug'),
        ('distributors', '0040_vendor_pflops_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pflops_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='pflops_product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.product'),
        ),
    ]
