# Generated by Django 3.2.7 on 2021-10-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0041_auto_20211003_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='pflops_category',
            new_name='to_pflops',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pflops_product',
            new_name='to_pflops',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='pflops_vendor',
            new_name='to_pflops',
        ),
    ]
