# Generated by Django 3.2.7 on 2021-10-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0005_vendor_slug'),
        ('distributors', '0042_auto_20211003_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='to_pflops',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.unit'),
        ),
    ]
