# Generated by Django 3.2.7 on 2021-10-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0043_unit_to_pflops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='group',
        ),
        migrations.DeleteModel(
            name='ParameterGroup',
        ),
    ]
