# Generated by Django 3.2.7 on 2021-10-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0044_auto_20211009_2208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('distributor', 'name')},
        ),
    ]
