# Generated by Django 3.2.7 on 2021-10-11 16:42

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0048_parameterunit_to_pflops'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='names_search',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='parameters_search',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['names_search', 'parameters_search'], name='pflops_product_search_idx'),
        ),
    ]
