# Generated by Django 3.2.7 on 2021-10-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0049_auto_20211011_1642'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='pflops_product_search_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='names_search',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameters_search',
        ),
    ]
