# Generated by Django 3.2.7 on 2021-10-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0050_auto_20211011_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='print_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='currency',
            name='key_digit',
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='quantity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.FloatField(default=None, null=True),
        ),
    ]
