# Generated by Django 3.2.7 on 2021-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0051_auto_20211016_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outoftrade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unconditional',
        ),
        migrations.AddField(
            model_name='party',
            name='condition_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='outoftrade',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='promo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='unconditional',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
