# Generated by Django 3.2.7 on 2021-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0052_auto_20211020_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='key_digit',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
