# Generated by Django 3.2.9 on 2021-12-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0053_alter_currency_key_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='distributors.currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
