# Generated by Django 3.2.9 on 2021-12-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0054_auto_20211210_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.FloatField(default=1.0),
        ),
    ]
