# Generated by Django 3.2.9 on 2021-12-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0055_auto_20211211_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
