# Generated by Django 3.2.9 on 2021-12-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0056_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='ext',
        ),
    ]
