# Generated by Django 3.2.9 on 2021-12-21 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ogrn', models.TextField(unique=True)),
                ('name', models.TextField(default=None, null=True)),
                ('inn', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('login', models.TextField(default=None, null=True)),
                ('password', models.TextField(default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(db_index=True, default=None, null=True)),
                ('file_name', models.TextField(default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parsed', models.DateTimeField(default=None, null=True)),
                ('source', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swarm.source')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_number', models.TextField(unique=True)),
                ('name', models.TextField(default=None, null=True)),
                ('okpd2', models.TextField(default=None, null=True)),
                ('tnved', models.TextField(default=None, null=True)),
                ('name_of_regulation', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swarm.organisation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.TextField(db_index=True, default=None, null=True)),
                ('file_name', models.TextField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parsed', models.DateTimeField(default=None, null=True)),
                ('source_data', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swarm.sourcedata')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
