# Generated by Django 3.0.3 on 2020-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='parsed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
