# Generated by Django 3.0.3 on 2020-04-20 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(default=None, null=True)),
                ('file_name', models.TextField(default=None, null=True)),
                ('source', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swarm.Source')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
    ]
