# Generated by Django 3.0.3 on 2020-04-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0002_data_parsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file_name',
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
