# Generated by Django 3.0.3 on 2020-04-25 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0003_auto_20200425_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedata',
            name='edited',
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
