# Generated by Django 3.0.3 on 2020-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0003_auto_20200428_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file_name',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
