# Generated by Django 3.0.3 on 2020-04-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0004_data_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
    ]
