# Generated by Django 3.0.3 on 2020-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0004_auto_20200425_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedata',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='url',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
