# Generated by Django 3.0.3 on 2020-04-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0005_remove_data_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='type',
            new_name='content_type',
        ),
    ]
