# Generated by Django 3.0.6 on 2020-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0006_auto_20200428_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedata',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
    ]
