# Generated by Django 3.2.7 on 2021-10-14 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0007_sourcedata_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ogrn', models.TextField(unique=True)),
                ('name', models.TextField(default=None, null=True)),
                ('inn', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_number', models.TextField(unique=True)),
                ('name', models.TextField(default=None, null=True)),
                ('okpd2', models.TextField(default=None, null=True)),
                ('tnved', models.TextField(default=None, null=True)),
                ('name_of_regulation', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_of_organisation', to='swarm.organisation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
