# Generated by Django 3.2.7 on 2021-10-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0008_organisation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swarm.organisation'),
        ),
    ]
