# Generated by Django 3.2.9 on 2021-12-21 13:30

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('level', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.category')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('key_digit', models.CharField(default=None, max_length=32, null=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('html', models.TextField(db_index=True, default=None, null=True)),
                ('full_name', models.TextField(db_index=True, default=None, null=True)),
                ('quantity', models.FloatField(default=1.0)),
                ('rate', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.currency')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.TextField(db_index=True, default=None, null=True)),
                ('names_search', models.TextField(db_index=True, default=None, null=True)),
                ('parameters_search', models.TextField(db_index=True, default=None, null=True)),
                ('slug', models.TextField(db_index=True, default=None, null=True)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('short_name', models.TextField(db_index=True, default=None, null=True)),
                ('name_rus', models.TextField(db_index=True, default=None, null=True)),
                ('name_other', models.TextField(db_index=True, default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('warranty', models.TextField(default=None, null=True)),
                ('ean_128', models.TextField(db_index=True, default=None, null=True)),
                ('upc', models.TextField(db_index=True, default=None, null=True)),
                ('pnc', models.TextField(db_index=True, default=None, null=True)),
                ('hs_code', models.TextField(db_index=True, default=None, null=True)),
                ('gtin', models.TextField(db_index=True, default=None, null=True)),
                ('tnved', models.TextField(db_index=True, default=None, null=True)),
                ('traceable', models.BooleanField(db_index=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('quantity_great_than', models.BooleanField(db_index=True, default=None, null=True)),
                ('weight', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('width', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('height', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('depth', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('volume', models.DecimalField(decimal_places=9, default=None, max_digits=18, null=True)),
                ('multiplicity', models.IntegerField(default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('content_loaded', models.DateTimeField(default=None, null=True)),
                ('images_loaded', models.DateTimeField(default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('edited', models.DateTimeField(default=None, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.category')),
                ('price', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.price')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, default=None, null=True)),
                ('full_name', models.TextField(db_index=True, default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('slug', models.TextField(db_index=True, default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.TextField(db_index=True, default=None, null=True)),
                ('file_name', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.product')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.vendor'),
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('parameter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.parameter')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.product')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.unit')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.parametergroup'),
        ),
        migrations.CreateModel(
            name='CatalogElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(db_index=True)),
                ('slug', models.TextField(db_index=True, default=None, null=True)),
                ('path', models.TextField(db_index=True, default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(db_index=True, default=None, null=True)),
                ('published', models.DateTimeField(db_index=True, default=None, null=True)),
                ('image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.image')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.catalogelement')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(db_index=True)),
                ('slug', models.TextField(db_index=True, default=None, null=True)),
                ('path', models.TextField(db_index=True, default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('assistant', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(db_index=True, default=None, null=True)),
                ('published', models.DateTimeField(db_index=True, default=None, null=True)),
                ('image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.image')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.catalogelement')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['names_search', 'parameters_search'], name='product_search_idx'),
        ),
    ]
