# Generated by Django 3.0.6 on 2021-04-07 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('description', models.TextField(default='')),
                ('number', models.BigIntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['number', 'name'],
            },
        ),
    ]
