# Generated by Django 4.0 on 2022-01-30 21:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_search_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['names_search', 'parameters_search', 'part_number'], name='product_search_idx'),
        ),
    ]
