# Generated by Django 3.2.7 on 2021-09-14 18:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(db_index=True)),
                ('slug', models.TextField(db_index=True, default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(db_index=True, default=None, null=True)),
                ('published', models.DateTimeField(db_index=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
