# Generated by Django 3.2.7 on 2021-10-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='article',
            name='Article',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='path',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
