# Generated by Django 3.2.7 on 2021-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0004_auto_20211003_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
