# Generated by Django 3.2.7 on 2021-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0005_vendor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
