# Generated by Django 3.2.7 on 2021-10-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0006_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametervalue',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pflops.product'),
        ),
    ]
