# Generated by Django 3.2.7 on 2021-10-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0007_parametervalue_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images_loaded',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
