# Generated by Django 3.2.7 on 2021-10-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0008_product_images_loaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='ext',
        ),
    ]
