# Generated by Django 3.2.7 on 2021-10-11 16:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0009_remove_productimage_ext'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_search_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='search',
            new_name='names_search',
        ),
        migrations.AddField(
            model_name='product',
            name='parameters_search',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['names_search', 'parameters_search'], name='product_search_idx'),
        ),
    ]
