# Generated by Django 3.2.7 on 2021-10-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0010_auto_20211011_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='currency',
            name='key_digit',
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
