# Generated by Django 3.2.7 on 2021-10-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0012_auto_20211016_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outoftrade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unconditional',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
