# Generated by Django 3.2.7 on 2021-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0013_auto_20211020_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='html',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
