# Generated by Django 3.2.7 on 2021-10-27 09:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0014_currency_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogElementImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
