# Generated by Django 3.2.7 on 2021-10-27 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0015_catalogelementimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('slug', models.TextField(db_index=True, default=None, null=True)),
                ('path', models.TextField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.catalogelementimage')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.catalogelement')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
