# Generated by Django 3.2.7 on 2021-10-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pflops', '0016_catalogelement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogElementImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='article',
            name='catalog_element',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pflops.image'),
        ),
        migrations.DeleteModel(
            name='CatalogElement',
        ),
    ]
