# Generated by Django 3.0.6 on 2021-02-13 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('figi', models.CharField(max_length=128, unique=True)),
                ('ticker', models.CharField(max_length=128, unique=True)),
                ('isin', models.CharField(default=None, max_length=128)),
                ('name', models.TextField(default=None, null=True)),
                ('type', models.CharField(default=None, max_length=128)),
                ('lot', models.BigIntegerField(default=None)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
