# Generated by Django 3.0.6 on 2021-03-08 14:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_auto_20210213_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ticker',
            field=models.CharField(db_index=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.CharField(db_index=True, default=None, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Orderbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('orderbook', models.TextField()),
                ('candles', models.TextField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Instrument')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
