# Generated by Django 3.0.6 on 2021-03-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_auto_20210308_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderbook',
            new_name='Snapshot',
        ),
    ]
