# Generated by Django 3.0.6 on 2021-03-20 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_auto_20210308_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('interval', models.CharField(db_index=True, max_length=8)),
                ('o', models.DecimalField(decimal_places=10, max_digits=20)),
                ('c', models.DecimalField(decimal_places=10, max_digits=20)),
                ('h', models.DecimalField(decimal_places=10, max_digits=20)),
                ('l', models.DecimalField(decimal_places=10, max_digits=20)),
                ('v', models.DecimalField(decimal_places=10, max_digits=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Instrument')),
            ],
        ),
    ]
